const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ctx={window:{}};
for(const name of ['data','records-data','calendar-records-model','dry-records-model'])vm.runInNewContext(fs.readFileSync(__dirname+'/../dist/'+name+'.js','utf8'),ctx);
const create=ctx.window.DryRecordModel.createDryRecords;
const r=create(ctx.window.RAIN_DATA,ctx.window.RECORD_DATA);
assert.equal(r.leaders.month.value,659);
assert.equal(r.leaders.month.holders[0].key,'04');
assert.equal(r.leaders.day.value,0);
assert.equal(r.leaders.day.holders.length,90);
assert.equal(r.leaders.week.value,0);
assert.equal(r.leaders.week.holders.length,3);
assert.equal(r.streak.leader.value,24);
assert.equal(r.streak.record.value,34);
assert.equal(r.annual.record.value,14874);
assert.equal(r.annual.record.holders[0].start,'1915-01-01');
assert.equal(r.annual.complete,false);
assert.deepEqual(Array.from(r.broken,r=>r.key),['29','5']);
assert.ok(r.broken.every(x=>x.current.complete&&x.current.value<x.record.value));
assert.equal(r.months[9].status,'pending');
assert.equal(r.weeks[40].status,'pending');
const dayRows=(start,end,value)=>{const rows=[];for(let d=start;d<=end;d=ctx.window.CalendarRecordModel.next(d))rows.push([d,value]);return rows};
const source={first:'2024-01-01',last:'2026-01-08',dailyTenths:[...dayRows('2024-01-01','2024-01-31',10),...dayRows('2025-01-01','2025-01-31',10),...dayRows('2026-01-01','2026-01-08',0)]};
const monthly=[{month:'2024-01',mm:31},{month:'2025-01',mm:31}];
const p=create(monthly,source);
assert.equal(p.months[0].status,'pending');
assert.equal(p.leaders.month,null);
assert.equal(p.weeks[1].status,'pending');
assert.ok(!p.broken.some(r=>r.type==='month'));
assert.equal(p.days[0].status,'broken');
assert.equal(p.days[0].current.value,0);
const missing={...source,dailyTenths:source.dailyTenths.map(([d,v])=>[d,d==='2026-01-04'?null:v])};
const m=create(monthly,missing);
assert.equal(m.annual.current,null);
assert.equal(m.leaders.rolling,null);
assert.equal(m.days[3].status,'unavailable');
assert.equal(m.streak.leader.value,4);
const tie=create([], {first:'2025-01-01',last:'2026-01-01',dailyTenths:[['2025-01-01',0],['2026-01-01',0]]});
assert.equal(tie.days[0].status,'tied');
assert.equal(tie.broken.length,0);
assert.equal(tie.tied.length,1);
console.log('Passed dry records: completed periods, zero ties, prior-year minima, missing data, dry streaks and annual comparisons.');
